Repository Azure/gpu-provisioner, pull requests merged in 2025-05, with the labels that each got.

#232 chore: bump golang.org/x/net from 0.36.0 to 0.38.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/h2c/h2c.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: Review effort 2/5

#233 fix: the storage value conversion
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
Labels: Review effort 3/5

#234 fix: storage request in nodeclaim should be more than 0
  examples/v1-nodeclaim-gpu.yaml
  pkg/cloudprovider/cloudprovider_test.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
  test/e2e/suites/suite_test.go
Labels: Review effort 4/5

#235 release: update manifest and helm charts for v0.3.4
  Makefile
  charts/gpu-provisioner/Chart.yaml
  charts/gpu-provisioner/values.yaml
Labels: Review effort 1/5

#238 release: update manifest and helm charts for v0.3.5
  Makefile
  charts/gpu-provisioner/Chart.yaml
  charts/gpu-provisioner/values.yaml
Labels: Review effort 1/5
